### ISSUE TITLE
Support for autoscaling by more than 1 instance

### ISSUE THREAD

**Issue by alenkacz** [alenkacz/marathon-rabbitmq-autoscale#22]
Similarly as orbiter does https://gianarb.it/blog/orbiter-docker-swarm-autoscaler

orbiter.up=3 and orbiter.down=2.

**Comment by rpliva** [comment]
This issue can be closed

**Comment by alenkacz** [comment]
Fixed in #35

**Comment by alenkacz** [comment]
@rpliva thanks!
